if (NOT DEFINED INSTALL_DESTINATION)
    set(INSTALL_DESTINATION ${CMAKE_INSTALL_PREFIX})
endif()

install(CODE "
    set(CMAKE_PREFIX_PATH ${CMAKE_PREFIX_PATH})
    set(TARGET_FILE $<TARGET_FILE:${PROJECT_NAME}>)
    set(INSTALL_DESTINATION ${INSTALL_DESTINATION})
")